### ISSUE TITLE
A question about the reduction's best choice

### ISSUE THREAD

**Issue by woson-L** [Andrew-Qibin/CoordAttention#11]
Hello, I recently added your CA in target detection and experimented with the reduction to 32,16,8.The model was evaluated by MAP_0.5, Precison, and Recall related indicators.It is found that the situation where r=16 is the optimal one, 8 is better than 32 but weaker than 16. However, your paper said ''This demonstrates that adding more parameters by reducing the reduction ratio matters for improving the model performance''.However, the map, precison, and recall values of r=8 are weaker than those of r=16.
Hope to get your reply as soon as possible,Thank you！

**Comment by Andrew-Qibin** [comment]
It dependes on the target task. Our experiments are based on ImageNet classification.

**Comment by woson-L** [comment]
> It dependes on the target task. Our experiments are based on ImageNet classification.



> It dependes on the target task. Our experiments are based on ImageNet classification.

**Comment by woson-L** [comment]
> It dependes on the target task. Our experiments are based on ImageNet classification.

Thank you for your reply!
So, can I take it that conclusion may not apply when I'm using a different network than ImageNet?.
Have you ever tested the case of r=8, in which the model evaluation decreased when r was reduced.For example, F1 at r=24 is better than r=16.
Hope to get your reply as soon as possible,Thank you！

**Comment by Andrew-Qibin** [comment]
Sorry, I did not do that before. Just choose the best ratio for your own model.

**Comment by woson-L** [comment]
> Sorry, I did not do that before. Just choose the best ratio for your own model.
Thank you for your reply!OK, I see. I will do it. 
Finally, thank you for the great help this project has brought me!Thank you！
