### ISSUE TITLE
What's the meaning of the Concatenation and Split operation?

### ISSUE THREAD

**Issue by BluebirdStory** [Andrew-Qibin/CoordAttention#12]
Hey, Good Work!
However, I still don't understand the meaning of concatenation. After X AVG POOL and Y AVG POOL, we got two feature maps whose shapes like (C, H, 1) and (C, 1, W), and then you choose to concatenate them in the spatial dimension and get feature map shape like (C, H+W, 1), after that you apply a 1x1 convolution filter to it. Since the conv filter is applied to the channel dimension and it has kernel size of 1x1, there is actually no information exchange in the spatial dimension like the Spatial Attention Module in CBAM. The only spatial information exchange happens in the BatchNorm in CoordAttention, which I think is trivial.
Actually I think the Concatenation and Split operation is redundant, why you choose such a design?

**Comment by Andrew-Qibin** [comment]
We use x avg pool and y avg pool to encode spatial information. About the concat and split, this is identical to using two separate 1x1 convs for each branch with shared weights. The truth is using concat and split can accelerate the running speed compared to using two separate convs.

**Comment by BluebirdStory** [comment]
Alright, I get your point now. At the beginning,  It seems quite strange to me, because modern inference library such as Openvion and TensorRT can help do these acceleration.
Anyway, thank you for your reply.
