### ISSUE TITLE
Where is the best position to insert the CoordAttention？

### ISSUE THREAD

**Issue by Fly-Pluche** [Andrew-Qibin/CoordAttention#17]
Could you give me some advice about where to insert the CoordAttention?Did it will perform best on the begin of the net ,on the end of the net or before the Conv?

**Comment by Andrew-Qibin** [comment]
According to my experience, adding CoordAtt to the top building blocks works better than adding that to the bottom ones.

**Comment by Fly-Pluche** [comment]
Thanks for your answer.
