### ISSUE TITLE
Is there a performance improvement for CA

### ISSUE THREAD

**Issue by fanghua2021** [Andrew-Qibin/CoordAttention#26]
I added the CA module to GhostNet, and the Map dropped. At the same time, adding the CA module to the Neck's Concat function also decreased the accuracy. Why? 
But, adding SEnet can increase the accuracy.

**Comment by Fateeeeee** [comment]
my MAP also drop 2 point

**Comment by Fateeeeee** [comment]
Do you solve it? I also met this problem.

**Comment by fanghua2021** [comment]
No, I'm still reading the original article. Call the original author team for help

**Comment by houqb** [comment]
Not sure what happened. Be sure to add them after layers with channel expansion.
