### ISSUE TITLE
TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by huanmx** [Andrew-Qibin/CoordAttention#34]
Hi! 
When I add CA module to the backbone, I got TypeError: "must be real number, not NoneType". The error occurs in nn.AdaptiveAvgPool2d((None, 1)). How to solve the problem?

**Comment by xxxjjjx** [comment]
Have you solved this problem？

**Comment by vaerdu** [comment]
我也遇到了同样的问题，请问你解决了吗？

**Comment by vaerdu** [comment]
> Hi! When I add CA module to the backbone, I got TypeError: "must be real number, not NoneType". The error occurs in nn.AdaptiveAvgPool2d((None, 1)). How to solve the problem?

我也遇到了同样的问题，请问你解决了吗？

**Comment by vaerdu** [comment]
> Have you solved this problem？

请问这个问题你解决了吗？
